export interface Name99 {
  no: number;
  arabic: string;
  translit: string;
  meaning: string;
  wazifa: string;
}

export const NAMES_99: Name99[] = [
  { no: 1, arabic: "الرَّحْمَن", translit: "Ar-Rahman", meaning: "The Most Compassionate", wazifa: "Recite 298 times daily for mercy and blessings in life." },
  { no: 2, arabic: "الرَّحِيم", translit: "Ar-Raheem", meaning: "The Most Merciful", wazifa: "Recite 258 times to attain Allah's special mercy." },
  { no: 3, arabic: "المَلِك", translit: "Al-Malik", meaning: "The King", wazifa: "Recite after Isha for respect and honour among people." },
  { no: 4, arabic: "القُدُّوس", translit: "Al-Quddus", meaning: "The Most Holy", wazifa: "Recite 100 times daily for purity of heart and soul." },
  { no: 5, arabic: "السَّلَام", translit: "As-Salam", meaning: "The Source of Peace", wazifa: "Recite 136 times to be protected from anxiety and fear." },
  { no: 6, arabic: "المُؤْمِن", translit: "Al-Mu'min", meaning: "The Guardian of Faith", wazifa: "Recite for protection of faith and family." },
  { no: 7, arabic: "المُهَيْمِن", translit: "Al-Muhaymin", meaning: "The Protector", wazifa: "Recite 145 times after Ghusl for spiritual protection." },
  { no: 8, arabic: "العَزِيز", translit: "Al-Aziz", meaning: "The Almighty", wazifa: "Recite 40 times after Fajr to gain strength and dignity." },
  { no: 9, arabic: "الجَبَّار", translit: "Al-Jabbar", meaning: "The Compeller", wazifa: "Recite for victory over difficulties and enemies." },
  { no: 10, arabic: "المُتَكَبِّر", translit: "Al-Mutakabbir", meaning: "The Majestic", wazifa: "Recite to be protected from arrogance and given humility." },
  { no: 11, arabic: "الخَالِق", translit: "Al-Khaliq", meaning: "The Creator", wazifa: "Recite at night for a child or an increase in blessings." },
  { no: 12, arabic: "البَارِئ", translit: "Al-Bari'", meaning: "The Evolver", wazifa: "Recite for relief from sickness and affliction." },
  { no: 13, arabic: "المُصَوِّر", translit: "Al-Musawwir", meaning: "The Fashioner", wazifa: "Recite 21 times daily for beauty of character and face." },
  { no: 14, arabic: "الغَفَّار", translit: "Al-Ghaffar", meaning: "The Ever-Forgiving", wazifa: "Recite 100 times after Jumu'ah for forgiveness of sins." },
  { no: 15, arabic: "القَهَّار", translit: "Al-Qahhar", meaning: "The Subduer", wazifa: "Recite for control over anger and bad habits." },
  { no: 16, arabic: "الوَهَّاب", translit: "Al-Wahhab", meaning: "The Bestower", wazifa: "Recite 7 times after Fajr for wealth and generosity." },
  { no: 17, arabic: "الرَّزَّاق", translit: "Ar-Razzaq", meaning: "The Provider", wazifa: "Recite 308 times at dawn for abundant provision." },
  { no: 18, arabic: "الفَتَّاح", translit: "Al-Fattah", meaning: "The Opener", wazifa: "Recite for success in exams, work and opening of doors." },
  { no: 19, arabic: "العَلِيم", translit: "Al-'Alim", meaning: "The All-Knowing", wazifa: "Recite 100 times for increased knowledge and memory." },
  { no: 20, arabic: "القَابِض", translit: "Al-Qabid", meaning: "The Constrictor", wazifa: "Recite for control over hardships and difficulties." },
  { no: 21, arabic: "البَاسِط", translit: "Al-Basit", meaning: "The Expander", wazifa: "Recite for expansion of sustenance and happiness." },
  { no: 22, arabic: "الخَافِض", translit: "Al-Khafid", meaning: "The Abaser", wazifa: "Recite for protection from pride and oppression." },
  { no: 23, arabic: "الرَّافِع", translit: "Ar-Rafi'", meaning: "The Exalter", wazifa: "Recite 70 times after Maghrib for honour and rank." },
  { no: 24, arabic: "المُعِزّ", translit: "Al-Mu'izz", meaning: "The Giver of Honour", wazifa: "Recite 140 times for dignity and respect." },
  { no: 25, arabic: "المُذِلّ", translit: "Al-Mudhill", meaning: "The Abaser of Pride", wazifa: "Recite for victory over tyrants and oppressors." },
  { no: 26, arabic: "السَّمِيع", translit: "As-Sami'", meaning: "The All-Hearing", wazifa: "Recite on Thursday for acceptance of prayers." },
  { no: 27, arabic: "البَصِير", translit: "Al-Basir", meaning: "The All-Seeing", wazifa: "Recite for clarity of vision and insight." },
  { no: 28, arabic: "الحَكَم", translit: "Al-Hakam", meaning: "The Judge", wazifa: "Recite for justice in disputes and right decisions." },
  { no: 29, arabic: "العَدْل", translit: "Al-'Adl", meaning: "The Just", wazifa: "Recite for fairness and success in legal matters." },
  { no: 30, arabic: "اللَّطِيف", translit: "Al-Latif", meaning: "The Subtle", wazifa: "Recite 129 times daily for gentle solutions to problems." },
  { no: 31, arabic: "الخَبِير", translit: "Al-Khabir", meaning: "The All-Aware", wazifa: "Recite for inner awareness and protection from harm." },
  { no: 32, arabic: "الحَلِيم", translit: "Al-Halim", meaning: "The Forbearing", wazifa: "Recite for patience and calmness in life." },
  { no: 33, arabic: "العَظِيم", translit: "Al-'Azim", meaning: "The Magnificent", wazifa: "Recite for honour, greatness and protection." },
  { no: 34, arabic: "الغَفُور", translit: "Al-Ghafur", meaning: "The All-Forgiving", wazifa: "Recite 100 times daily for forgiveness of sins." },
  { no: 35, arabic: "الشَّكُور", translit: "Ash-Shakur", meaning: "The Appreciative", wazifa: "Recite 41 times for gratitude and increase in blessings." },
  { no: 36, arabic: "العَلِيّ", translit: "Al-'Aliyy", meaning: "The Most High", wazifa: "Recite 110 times for success and high rank." },
  { no: 37, arabic: "الكَبِير", translit: "Al-Kabir", meaning: "The Greatest", wazifa: "Recite 232 times for dignity and honour." },
  { no: 38, arabic: "الحَفِيظ", translit: "Al-Hafiz", meaning: "The Preserver", wazifa: "Recite 99 times daily for protection of family and wealth." },
  { no: 39, arabic: "المُقِيت", translit: "Al-Muqit", meaning: "The Sustainer", wazifa: "Recite 7 times on food for barakah and nourishment." },
  { no: 40, arabic: "الحَسِيب", translit: "Al-Hasib", meaning: "The Reckoner", wazifa: "Recite for protection from fear and sufficient provision." },
  { no: 41, arabic: "الجَلِيل", translit: "Al-Jalil", meaning: "The Majestic", wazifa: "Recite for honour, dignity and respect among people." },
  { no: 42, arabic: "الكَرِيم", translit: "Al-Karim", meaning: "The Most Generous", wazifa: "Recite for generosity and increase in good fortune." },
  { no: 43, arabic: "الرَّقِيب", translit: "Ar-Raqib", meaning: "The Watchful", wazifa: "Recite 7 times daily for protection from harm." },
  { no: 44, arabic: "المُجِيب", translit: "Al-Mujib", meaning: "The Responsive", wazifa: "Recite 55 times for acceptance of duas." },
  { no: 45, arabic: "الوَاسِع", translit: "Al-Wasi'", meaning: "The All-Encompassing", wazifa: "Recite for expansion of rizq and peace of mind." },
  { no: 46, arabic: "الحَكِيم", translit: "Al-Hakim", meaning: "The Wise", wazifa: "Recite for wisdom in decisions and knowledge." },
  { no: 47, arabic: "الوَدُود", translit: "Al-Wadud", meaning: "The Loving", wazifa: "Recite 100 times for love and harmony in the home." },
  { no: 48, arabic: "المَجِيد", translit: "Al-Majid", meaning: "The Glorious", wazifa: "Recite for glory, honour and blessings." },
  { no: 49, arabic: "البَاعِث", translit: "Al-Ba'ith", meaning: "The Resurrector", wazifa: "Recite at night for renewed energy and revival." },
  { no: 50, arabic: "الشَّهِيد", translit: "Ash-Shahid", meaning: "The Witness", wazifa: "Recite for justice, honesty and truthfulness." },
  { no: 51, arabic: "الحَقّ", translit: "Al-Haqq", meaning: "The Truth", wazifa: "Recite for truthfulness and the truth to prevail." },
  { no: 52, arabic: "الوَكِيل", translit: "Al-Wakil", meaning: "The Trustee", wazifa: "Recite 66 times for trust in Allah and protection." },
  { no: 53, arabic: "القَوِيّ", translit: "Al-Qawiyy", meaning: "The Strong", wazifa: "Recite for physical and spiritual strength." },
  { no: 54, arabic: "المَتِين", translit: "Al-Matin", meaning: "The Firm", wazifa: "Recite for firmness of faith and resolve." },
  { no: 55, arabic: "الوَلِيّ", translit: "Al-Waliyy", meaning: "The Protecting Friend", wazifa: "Recite 7 times for Allah's friendship and help." },
  { no: 56, arabic: "الحَمِيد", translit: "Al-Hamid", meaning: "The Praiseworthy", wazifa: "Recite for acceptance of good deeds and praise." },
  { no: 57, arabic: "المُحْصِي", translit: "Al-Muhsi", meaning: "The Accounter", wazifa: "Recite for remembrance of Allah and counting blessings." },
  { no: 58, arabic: "المُبْدِئ", translit: "Al-Mubdi'", meaning: "The Originator", wazifa: "Recite for new beginnings and creativity." },
  { no: 59, arabic: "المُعِيد", translit: "Al-Mu'id", meaning: "The Restorer", wazifa: "Recite for return of lost things and restoration." },
  { no: 60, arabic: "المُحْيِي", translit: "Al-Muhyi", meaning: "The Giver of Life", wazifa: "Recite for health, life and recovery from illness." },
  { no: 61, arabic: "المُمِيت", translit: "Al-Mumit", meaning: "The Bringer of Death", wazifa: "Recite for control over desires and self." },
  { no: 62, arabic: "الحَيُّ", translit: "Al-Hayy", meaning: "The Ever-Living", wazifa: "Recite 18 times daily for life and protection." },
  { no: 63, arabic: "القَيُّوم", translit: "Al-Qayyum", meaning: "The Sustainer of All", wazifa: "Recite for stability and protection from weakness." },
  { no: 64, arabic: "الوَاجِد", translit: "Al-Wajid", meaning: "The Finder", wazifa: "Recite for finding what is needed and contentment." },
  { no: 65, arabic: "المَاجِد", translit: "Al-Majid", meaning: "The Illustrious", wazifa: "Recite for honour, nobility and dignity." },
  { no: 66, arabic: "الوَاحِد", translit: "Al-Wahid", meaning: "The One", wazifa: "Recite 100 times in solitude for unity of heart." },
  { no: 67, arabic: "الأَحَد", translit: "Al-Ahad", meaning: "The Unique", wazifa: "Recite 1000 times for purity of Tawheed and peace." },
  { no: 68, arabic: "الصَّمَد", translit: "As-Samad", meaning: "The Eternal Refuge", wazifa: "Recite for sufficiency and independence from creation." },
  { no: 69, arabic: "القَادِر", translit: "Al-Qadir", meaning: "The All-Powerful", wazifa: "Recite for strength to overcome obstacles." },
  { no: 70, arabic: "المُقْتَدِر", translit: "Al-Muqtadir", meaning: "The Determiner", wazifa: "Recite for success in all affairs." },
  { no: 71, arabic: "المُقَدِّم", translit: "Al-Muqaddim", meaning: "The Advancer", wazifa: "Recite for progress and being put forward." },
  { no: 72, arabic: "المُؤَخِّر", translit: "Al-Mu'akhkhir", meaning: "The Deferrer", wazifa: "Recite for protection from haste and regret." },
  { no: 73, arabic: "الأَوَّل", translit: "Al-Awwal", meaning: "The First", wazifa: "Recite 11 times for remembrance of the beginning." },
  { no: 74, arabic: "الآخِر", translit: "Al-Akhir", meaning: "The Last", wazifa: "Recite for hope in the Hereafter and good end." },
  { no: 75, arabic: "الظَّاهِر", translit: "Az-Zahir", meaning: "The Manifest", wazifa: "Recite for clarity and revelation of truth." },
  { no: 76, arabic: "البَاطِن", translit: "Al-Batin", meaning: "The Hidden", wazifa: "Recite for inner knowledge and spiritual awareness." },
  { no: 77, arabic: "الوَالِي", translit: "Al-Wali", meaning: "The Governor", wazifa: "Recite for protection of one's affairs." },
  { no: 78, arabic: "المُتَعَالِي", translit: "Al-Muta'ali", meaning: "The Most Exalted", wazifa: "Recite for elevation and high rank." },
  { no: 79, arabic: "البَرّ", translit: "Al-Barr", meaning: "The Source of Goodness", wazifa: "Recite for kindness, goodness and protection from evil." },
  { no: 80, arabic: "التَّوَّاب", translit: "At-Tawwab", meaning: "The Ever-Returning", wazifa: "Recite 7 times for acceptance of repentance." },
  { no: 81, arabic: "المُنْتَقِم", translit: "Al-Muntaqim", meaning: "The Avenger", wazifa: "Recite for victory over oppressors (against injustice)." },
  { no: 82, arabic: "العَفُوّ", translit: "Al-'Afuww", meaning: "The Pardoner", wazifa: "Recite 153 times for forgiveness of sins." },
  { no: 83, arabic: "الرَّؤُوف", translit: "Ar-Ra'uf", meaning: "The Most Kind", wazifa: "Recite 10 times daily for kindness and compassion." },
  { no: 84, arabic: "مَالِكُ المُلْك", translit: "Malik-ul-Mulk", meaning: "The Owner of All Sovereignty", wazifa: "Recite for authority, wealth and control of affairs." },
  { no: 85, arabic: "ذُو الجَلَالِ وَالإِكْرَام", translit: "Dhul-Jalali wal-Ikram", meaning: "The Lord of Majesty and Honour", wazifa: "Recite for honour, grandeur and protection." },
  { no: 86, arabic: "المُقْسِط", translit: "Al-Muqsit", meaning: "The Equitable", wazifa: "Recite for fairness and justice in dealings." },
  { no: 87, arabic: "الجَامِع", translit: "Al-Jami'", meaning: "The Gatherer", wazifa: "Recite for uniting hearts and finding lost things." },
  { no: 88, arabic: "الغَنِيّ", translit: "Al-Ghaniyy", meaning: "The Self-Sufficient", wazifa: "Recite for freedom from need and contentment." },
  { no: 89, arabic: "المُغْنِي", translit: "Al-Mughni", meaning: "The Enricher", wazifa: "Recite 1000 times for wealth and sufficiency." },
  { no: 90, arabic: "المَانِع", translit: "Al-Mani'", meaning: "The Preventer", wazifa: "Recite for protection from harm and evil." },
  { no: 91, arabic: "الضَّار", translit: "Ad-Darr", meaning: "The Distresser", wazifa: "Recite only in full submission; brings protection from loss." },
  { no: 92, arabic: "النَّافِع", translit: "An-Nafi'", meaning: "The Benefactor", wazifa: "Recite for benefit, goodness and success." },
  { no: 93, arabic: "النُّور", translit: "An-Nur", meaning: "The Light", wazifa: "Recite for spiritual light and guidance." },
  { no: 94, arabic: "الهَادِي", translit: "Al-Hadi", meaning: "The Guide", wazifa: "Recite 11 times after prayer for guidance." },
  { no: 95, arabic: "البَدِيع", translit: "Al-Badi'", meaning: "The Incomparable", wazifa: "Recite for creativity and innovative solutions." },
  { no: 96, arabic: "البَاقِي", translit: "Al-Baqi", meaning: "The Everlasting", wazifa: "Recite for permanence and protection from loss." },
  { no: 97, arabic: "الوَارِث", translit: "Al-Warith", meaning: "The Inheritor", wazifa: "Recite for preservation and inheritance of blessings." },
  { no: 98, arabic: "الرَّشِيد", translit: "Ar-Rashid", meaning: "The Guide to the Right Path", wazifa: "Recite for right decisions and correct actions." },
  { no: 99, arabic: "الصَّبُور", translit: "As-Sabur", meaning: "The Patient", wazifa: "Recite 100 times for patience and endurance." },
];

export function searchNames(query: string): Name99[] {
  const q = query.trim().toLowerCase();
  if (!q) return NAMES_99;
  return NAMES_99.filter(
    (n) =>
      n.translit.toLowerCase().includes(q) ||
      n.meaning.toLowerCase().includes(q) ||
      n.arabic.includes(q) ||
      String(n.no) === q
  );
}
