export interface SurahPageMap {
  number: number;
  name: string;
  englishName: string;
  page: number;
}

export const SURAH_PAGE_MAP: SurahPageMap[] = [
  { number: 1, name: "الفاتحة", englishName: "Al-Fatiha", page: 1 },
  { number: 2, name: "البقرة", englishName: "Al-Baqarah", page: 2 },
  { number: 3, name: "آل عمران", englishName: "Ali 'Imran", page: 50 },
  { number: 4, name: "النساء", englishName: "An-Nisa", page: 77 },
  { number: 5, name: "المائدة", englishName: "Al-Ma'idah", page: 106 },
  { number: 6, name: "الأنعام", englishName: "Al-An'am", page: 128 },
  { number: 7, name: "الأعراف", englishName: "Al-A'raf", page: 151 },
  { number: 8, name: "الأنفال", englishName: "Al-Anfal", page: 177 },
  { number: 9, name: "التوبة", englishName: "At-Tawbah", page: 187 },
  { number: 10, name: "يونس", englishName: "Yunus", page: 208 },
  { number: 11, name: "هود", englishName: "Hud", page: 221 },
  { number: 12, name: "يوسف", englishName: "Yusuf", page: 235 },
  { number: 13, name: "الرعد", englishName: "Ar-Ra'd", page: 249 },
  { number: 14, name: "إبراهيم", englishName: "Ibrahim", page: 255 },
  { number: 15, name: "الحجر", englishName: "Al-Hijr", page: 262 },
  { number: 16, name: "النحل", englishName: "An-Nahl", page: 267 },
  { number: 17, name: "الإسراء", englishName: "Al-Isra", page: 282 },
  { number: 18, name: "الكهف", englishName: "Al-Kahf", page: 293 },
  { number: 19, name: "مريم", englishName: "Maryam", page: 305 },
  { number: 20, name: "طه", englishName: "Taha", page: 312 },
  { number: 21, name: "الأنبياء", englishName: "Al-Anbiya", page: 322 },
  { number: 22, name: "الحج", englishName: "Al-Hajj", page: 332 },
  { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", page: 342 },
  { number: 24, name: "النور", englishName: "An-Nur", page: 350 },
  { number: 25, name: "الفرقان", englishName: "Al-Furqan", page: 359 },
  { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", page: 367 },
  { number: 27, name: "النمل", englishName: "An-Naml", page: 377 },
  { number: 28, name: "القصص", englishName: "Al-Qasas", page: 385 },
  { number: 29, name: "العنكبوت", englishName: "Al-'Ankabut", page: 396 },
  { number: 30, name: "الروم", englishName: "Ar-Rum", page: 404 },
  { number: 31, name: "لقمان", englishName: "Luqman", page: 411 },
  { number: 32, name: "السجدة", englishName: "As-Sajdah", page: 415 },
  { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", page: 418 },
  { number: 34, name: "سبإ", englishName: "Saba", page: 428 },
  { number: 35, name: "فاطر", englishName: "Fatir", page: 434 },
  { number: 36, name: "يس", englishName: "Ya-Sin", page: 440 },
  { number: 37, name: "الصافات", englishName: "As-Saffat", page: 445 },
  { number: 38, name: "ص", englishName: "Sad", page: 453 },
  { number: 39, name: "الزمر", englishName: "Az-Zumar", page: 458 },
  { number: 40, name: "غافر", englishName: "Ghafir", page: 467 },
  { number: 41, name: "فصلت", englishName: "Fussilat", page: 477 },
  { number: 42, name: "الشورى", englishName: "Ash-Shura", page: 483 },
  { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", page: 489 },
  { number: 44, name: "الدخان", englishName: "Ad-Dukhan", page: 496 },
  { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", page: 499 },
  { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", page: 502 },
  { number: 47, name: "محمد", englishName: "Muhammad", page: 507 },
  { number: 48, name: "الفتح", englishName: "Al-Fath", page: 511 },
  { number: 49, name: "الحجرات", englishName: "Al-Hujurat", page: 515 },
  { number: 50, name: "ق", englishName: "Qaf", page: 518 },
  { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", page: 520 },
  { number: 52, name: "الطور", englishName: "At-Tur", page: 523 },
  { number: 53, name: "النجم", englishName: "An-Najm", page: 526 },
  { number: 54, name: "القمر", englishName: "Al-Qamar", page: 528 },
  { number: 55, name: "الرحمن", englishName: "Ar-Rahman", page: 531 },
  { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", page: 534 },
  { number: 57, name: "الحديد", englishName: "Al-Hadid", page: 537 },
  { number: 58, name: "المجادلة", englishName: "Al-Mujadila", page: 542 },
  { number: 59, name: "الحشر", englishName: "Al-Hashr", page: 545 },
  { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", page: 549 },
  { number: 61, name: "الصف", englishName: "As-Saff", page: 551 },
  { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", page: 553 },
  { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", page: 554 },
  { number: 64, name: "التغابن", englishName: "At-Taghabun", page: 556 },
  { number: 65, name: "الطلاق", englishName: "At-Talaq", page: 558 },
  { number: 66, name: "التحريم", englishName: "At-Tahrim", page: 560 },
  { number: 67, name: "الملك", englishName: "Al-Mulk", page: 562 },
  { number: 68, name: "القلم", englishName: "Al-Qalam", page: 564 },
  { number: 69, name: "الحاقة", englishName: "Al-Haqqah", page: 566 },
  { number: 70, name: "المعارج", englishName: "Al-Ma'arij", page: 568 },
  { number: 71, name: "نوح", englishName: "Nuh", page: 570 },
  { number: 72, name: "الجن", englishName: "Al-Jinn", page: 572 },
  { number: 73, name: "المزمل", englishName: "Al-Muzzammil", page: 574 },
  { number: 74, name: "المدثر", englishName: "Al-Muddaththir", page: 575 },
  { number: 75, name: "القيامة", englishName: "Al-Qiyamah", page: 577 },
  { number: 76, name: "الإنسان", englishName: "Al-Insan", page: 578 },
  { number: 77, name: "المرسلات", englishName: "Al-Mursalat", page: 580 },
  { number: 78, name: "النبإ", englishName: "An-Naba", page: 582 },
  { number: 79, name: "النازعات", englishName: "An-Nazi'at", page: 583 },
  { number: 80, name: "عبس", englishName: "'Abasa", page: 585 },
  { number: 81, name: "التكوير", englishName: "At-Takwir", page: 586 },
  { number: 82, name: "الإنفطار", englishName: "Al-Infitar", page: 587 },
  { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", page: 587 },
  { number: 84, name: "الإنشقاق", englishName: "Al-Inshiqaq", page: 589 },
  { number: 85, name: "البروج", englishName: "Al-Buruj", page: 590 },
  { number: 86, name: "الطارق", englishName: "At-Tariq", page: 591 },
  { number: 87, name: "الأعلى", englishName: "Al-A'la", page: 591 },
  { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", page: 592 },
  { number: 89, name: "الفجر", englishName: "Al-Fajr", page: 593 },
  { number: 90, name: "البلد", englishName: "Al-Balad", page: 594 },
  { number: 91, name: "الشمس", englishName: "Ash-Shams", page: 595 },
  { number: 92, name: "الليل", englishName: "Al-Layl", page: 595 },
  { number: 93, name: "الضحى", englishName: "Ad-Duha", page: 596 },
  { number: 94, name: "الشرح", englishName: "Ash-Sharh", page: 596 },
  { number: 95, name: "التين", englishName: "At-Tin", page: 597 },
  { number: 96, name: "العلق", englishName: "Al-'Alaq", page: 597 },
  { number: 97, name: "القدر", englishName: "Al-Qadr", page: 598 },
  { number: 98, name: "البينة", englishName: "Al-Bayyinah", page: 598 },
  { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", page: 599 },
  { number: 100, name: "العاديات", englishName: "Al-'Adiyat", page: 599 },
  { number: 101, name: "القارعة", englishName: "Al-Qari'ah", page: 600 },
  { number: 102, name: "التكاثر", englishName: "At-Takathur", page: 600 },
  { number: 103, name: "العصر", englishName: "Al-'Asr", page: 601 },
  { number: 104, name: "الهمزة", englishName: "Al-Humazah", page: 601 },
  { number: 105, name: "الفيل", englishName: "Al-Fil", page: 601 },
  { number: 106, name: "قريش", englishName: "Quraysh", page: 602 },
  { number: 107, name: "الماعون", englishName: "Al-Ma'un", page: 602 },
  { number: 108, name: "الكوثر", englishName: "Al-Kawthar", page: 602 },
  { number: 109, name: "الكافرون", englishName: "Al-Kafirun", page: 603 },
  { number: 110, name: "النصر", englishName: "An-Nasr", page: 603 },
  { number: 111, name: "المسد", englishName: "Al-Masad", page: 603 },
  { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", page: 604 },
  { number: 113, name: "الفلق", englishName: "Al-Falaq", page: 604 },
  { number: 114, name: "الناس", englishName: "An-Nas", page: 604 },
];

/**
 * Helper function: Current page number ke basis par Surah information nikalne ke liye
 */
export function getSurahByPage(pageNumber: number): SurahPageMap {
  for (let i = SURAH_PAGE_MAP.length - 1; i >= 0; i--) {
    if (pageNumber >= SURAH_PAGE_MAP[i].page) {
      return SURAH_PAGE_MAP[i];
    }
  }
  return SURAH_PAGE_MAP[0];
}